### ISSUE TITLE
Add npm start script?

### ISSUE THREAD

**Issue by pdehaan** [n1k0/readinglist-client#26]
Not sure if we should add a handy `npm start` script to package.json for convention sake.

I don't know what it should do, but I imagine it could proxy either `npm run build` (which calls `$ gulp dist`) or `npm run dev` (which calls `$ gulp`).

Currently, running `npm start` gives me this npm error:

``` sh
$ npm start

npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/pdehaan/.nvm/versions/node/v0.12.0/bin/node" "/Users/pdehaan/.nvm/versions/node/v0.12.0/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pdehaan/dev/github/readinglist-client/npm-debug.log
```

**Comment by n1k0** [comment]
We have `npm run dev` which is basically a shorthand for `NODE_ENV=development gulp`; Though as `npm start` is is much more well established convention, we should switch to that. Will address.
