### ISSUE TITLE
404 when trying to load Bootstrap CSS sourcemap

### ISSUE THREAD

**Issue by pdehaan** [n1k0/readinglist-client#27]
### Steps to reproduce:
1. `$ npm run dev`
2. Open http://localhost:4000/ in a browser
3. Open the developer console
### Actual results:

| TIME | METHOD | URL | ERR |
| --: | :-: | --- | --- |
| 15:41:17.058 | GET | http://localhost:4000/css/bootstrap.css.map | [HTTP/1.1 404 Not Found 1ms] |
| 15:41:17.060 | GET | http://localhost:4000/css/bootstrap.css.map | [HTTP/1.1 404 Not Found 1ms] |
| 15:41:17.060 | GET | http://localhost:4000/css/bootstrap.css.map | [HTTP/1.1 404 Not Found 1ms] |

I'm guessing this is probably as easy as adding the sourcemap path to the gulpfile's [`cssAssets` array](https://github.com/mozilla-services/readinglist-client/blob/9046a0238ec205948635af0fd2302fdb10e93996/gulpfile.js#L30-L33):

```
node_modules/bootstrap/dist/css/bootstrap.css.map
```

**Comment by n1k0** [comment]
Fixed by 9970cd74018cbfad1074b0dc23174638322ed5bb
