### ISSUE TITLE
"Uncaught TypeError: undefined is not a function" in bundle.js:1

### ISSUE THREAD

**Issue by pdehaan** [n1k0/readinglist-client#47]
I'm currently seeing a white screen and a console barf when going to http://mozilla-services.github.io/readinglist-client/nightly/

![readinglist](https://cloud.githubusercontent.com/assets/557895/6517631/ecc41598-c351-11e4-8732-23937c156e14.png)

**Comment by n1k0** [comment]
I can't reproduce this, maybe that's a cache problem. Could you please try force-refreshing the page? Thanks.

**Comment by n1k0** [comment]
Hmm just got you're using Chrome, which I can now reproduce the issue with.
